# Generated by Django 5.1.3 on 2024-11-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Vehiculos',
        ),
    ]
